### ISSUE TITLE
unregisterReceiver() missing in some fragments

### ISSUE THREAD

**Issue by dheerajkotwani** [fossasia/neurolab-android#538]
**Describe the bug**
unregisterReceiver missing in some fragments

**Expected Behavior**
unregisterReceiver() must be present whenever we Register it

**Steps to reproduce it**
Try to navigate out by pressing back from FocusVisualFragment, MemoryGraphFragment, 

**LogCat for the issue**
```
E/ActivityThread: Activity io.neurolab.activities.ProgramModeActivity has leaked IntentReceiver io.neurolab.communication.DataReceiver@650bfc0 that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity io.neurolab.activities.ProgramModeActivity has leaked IntentReceiver io.neurolab.communication.DataReceiver@650bfc0 that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1437)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1214)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1486)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1459)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1447)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:633)
        at io.neurolab.fragments.FocusVisualFragment.recordData(FocusVisualFragment.java:196)
        at io.neurolab.fragments.FocusVisualFragment.lambda$buildInstructionDialog$2$FocusVisualFragment(FocusVisualFragment.java:311)
        at io.neurolab.fragments.-$$Lambda$FocusVisualFragment$wPcKrWYb3bi-NCAVzy4TQDptPNo.onClick(Unknown Source:2)
        at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6826)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

```
E/ActivityThread: Activity io.neurolab.activities.MemoryGraphParent has leaked IntentReceiver io.neurolab.communication.DataReceiver@bf44784 that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity io.neurolab.activities.MemoryGraphParent has leaked IntentReceiver io.neurolab.communication.DataReceiver@bf44784 that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1437)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1214)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1486)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1459)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1447)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:633)
        at io.neurolab.fragments.MemoryGraphFragment.recordData(MemoryGraphFragment.java:400)
        at io.neurolab.fragments.MemoryGraphFragment.onOptionsItemSelected(MemoryGraphFragment.java:459)
        at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:2587)
        at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:3368)
        at android.support.v4.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:356)
        at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:442)
        at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:196)
        at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at android.support.v7.app.AppCompatDelegateImpl.onMenuItemSelected(AppCompatDelegateImpl.java:888)
        at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
        at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:981)
        at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
        at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
        at android.view.View.performClick(View.java:6608)
        at android.view.View.performClickInternal(View.java:6585)
        at android.view.View.access$3100(View.java:785)
        at android.view.View$PerformClick.run(View.java:25919)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6826)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**System Information**
<table>
<tr>
  <td>Device</td><td>Xiaomi Redmi Y2</td>
</tr>
<tr>
  <td>Android version/OS</td><td>Pie 9.0</td>
</tr>
</table>

**Would you like to work on the issue?**
Yes

**Comment by dheerajkotwani** [comment]
@jddeep I had worked on it. Please review it.
