### ISSUE TITLE
App crashes on opening settings from navbar

### ISSUE THREAD

**Issue by ho-dor** [fossasia/neurolab-android#580]
**Describe the bug**
App crashes when settings opened from navbar

**Expected Behavior**
App should not crash

**Steps to reproduce it**
Open navbar, click on settings.

**LogCat for the issue**

java.lang.RuntimeException: Unable to resume activity {io.neurolab/io.neurolab.activities.SettingsActivity}: java.lang.NumberFormatException: For input string: ""
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4021)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4053)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7078)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)
     Caused by: java.lang.NumberFormatException: For input string: ""
        at java.lang.Integer.parseInt(Integer.java:627)
        at java.lang.Integer.valueOf(Integer.java:801)
        at io.neurolab.fragments.NeuroSettingsFragment.onResume(NeuroSettingsFragment.java:83)
        at android.support.v4.app.Fragment.performResume(Fragment.java:2498)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1501)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
        at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3241)
        at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:223)
        at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:538)
        at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:527)
        at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:172)
        at android.app.Activity.performResume(Activity.java:7597)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4013)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4053) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7078) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974) 

**System Information**
<table>
<tr>
  <td>Device</td><td>Samsung J8</td>
</tr>
<tr>
  <td>Android version/OS</td><td>9</td>
</tr>
</table>

**Would you like to work on the issue?**
Yes

**Comment by ho-dor** [comment]
This crash takes place if I set number of channels/bins empty and leave the settings menu, it does not show any error at that stage but when I try to re-open the settings menu, app crashes.I have to uninstall and then re-install to get the default values and open the settings menu. We have to not allow empty values for channels/bins at any point. @jddeep @CloudyPadmal

**Comment by kshitiz-kumar** [comment]
@ho-dor I think this issue has been mentioned earlier here https://github.com/fossasia/neurolab-android/issues/560 and this bug has been removed. Please check whether you have pulled the latest commits.
And if the error is something else please share a gif.

**Comment by bishtmanish739** [comment]
this app is working fine with me
