### ISSUE TITLE
Share Button on Navigation Drawer

### ISSUE THREAD

**Issue by jaspreetsidhu3** [fossasia/neurolab-android#646]
**Describe the bug**
On Clicking Share Button Application crashes 

**Expected Behavior**
The share option not showing

**Steps to reproduce it**

**LogCat for the issue**
java.lang.RuntimeException: Unable to start activity ComponentInfo{io.neurolab/io.neurolab.activities.ShareDataActivity}: java.lang.NullPointerException: Attempt to get length of null array
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3497)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3636)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2222)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:228)
        at android.app.ActivityThread.main(ActivityThread.java:7782)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
     Caused by: java.lang.NullPointerException: Attempt to get length of null array
        at io.neurolab.activities.ShareDataActivity.onCreate(ShareDataActivity.java:68)
        at android.app.Activity.performCreate(Activity.java:7964)
        at android.app.Activity.performCreate(Activity.java:7953)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3472)

**Screenshots of the issue**

**System Information**
<table>
<tr>
  <td>Device</td><td>Realme 3 pro</td>
</tr>
<tr>
  <td>Android version/OS</td><td>Android 10</td>
</tr>
</table>

**Would you like to work on the issue?**
Yes

**Comment by devptyagi** [comment]
Is it still available or already done?

**Comment by Prince-kushwaha** [comment]
I want to work on this problem

**Comment by DHRUV208** [comment]
I WANT TO SOLVE THE BUG

**Comment by ayushtyagi01** [comment]
I would like to solve this issue

**Comment by Pratham2305** [comment]
I think this issue still exists, I would like to resolve this one .

**Comment by ykirtii** [comment]
I would like to solve this.

**Comment by NikunjGarg2000** [comment]
Hey, assuming since no pr attached to the issue, I would like to solve this.
